// generated 2012/12/16 10:21:51 CET by danilo@dm1.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- wmpSniffer.glade
// for gtk 2.24.10 and gtkmm 2.24.2
//
// Please modify the corresponding derived classes in ./src/rec_param_dlg.hh and./src/rec_param_dlg.cc

#ifndef _REC_PARAM_DLG_GLADE_HH
#  define _REC_PARAM_DLG_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/button.h>
#include <gtkmm/buttonbox.h>
#include <gtkmm/label.h>
#include <gtkmm/spinbutton.h>
#include <gtkmm/radiobutton.h>
#include <gtkmm/entry.h>
#include <gtkmm/box.h>
#include <gtkmm/checkbutton.h>
#include <gtkmm/alignment.h>
#include <gtkmm/frame.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <gtkmm/expander.h>
#else //
#include <gtkmm/handlebox.h>
#endif //

class rec_param_dlg_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Dialog * rec_param_dlg;
        class Gtk::Button * cancelbutton1;
        class Gtk::Button * ok_btn;
        class Gtk::Label * label47;
        class Gtk::SpinButton * num_node_spin;
        class Gtk::RadioButton * real_rb;
        class Gtk::RadioButton * marte_rb;
        class Gtk::RadioButton * shmem_rb;
        class Gtk::Entry * shmem_file;
        class Gtk::Button * shmem_btn;
        class Gtk::HBox * hbox23;
        class Gtk::CheckButton * compile_cb;
        class Gtk::CheckButton * exec_cb;
        class Gtk::CheckButton * log_cb;
        class Gtk::HBox * hbox24;
        class Gtk::Entry * param_txt;
        class Gtk::Alignment * alignment23;
        class Gtk::Label * label95;
        class Gtk::Frame * frame14;
        class Gtk::Label * label94;
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
        class Gtk::Expander * expander1;
#else //
        class Gtk::HandleBox * expander1;
#endif //
        class Gtk::VBox * vbox19;
        class Gtk::Alignment * alignment20;
        class Gtk::Label * label91;
        class Gtk::Frame * frame13;
        class Gtk::VBox * vbox18;
        class Gtk::Alignment * alignment16;
        class Gtk::Label * label86;
        class Gtk::Frame * frame9;
        class Gtk::VBox * vbox17;
        class Gtk::Entry * filename_txt;
        class Gtk::Button * shmem_btn1;
        class Gtk::HBox * hbox1;
        class Gtk::VBox * vbox1;
        class Gtk::Alignment * alignment1;
        class Gtk::Label * label3;
        class Gtk::Frame * frame1;
        class Gtk::VBox * vbox6;
protected:
        
        rec_param_dlg_glade();
        
        ~rec_param_dlg_glade();
private:
        virtual void on_sim_rb_clicked() = 0;
        virtual void on_shmem_btn_clicked() = 0;
        virtual void on_filename_clicked() = 0;
};
#endif
