// generated 2012/12/16 11:18:14 CET by danilo@dm1.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- wmpSniffer.glade
// for gtk 2.24.10 and gtkmm 2.24.2
//
// Please modify the corresponding derived classes in ./src/window3.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "window3_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>

window3_glade::window3_glade(
)
{  window3 = this;
   gmm_data = new GlademmData(get_accel_group());
   align = Gtk::manage(new class Gtk::Alignment());
   label = Gtk::manage(new class Gtk::Label(""));
   frame15 = Gtk::manage(new class Gtk::Frame());
   nblabel = Gtk::manage(new class Gtk::Label("make"));
   notebook1 = Gtk::manage(new class Gtk::Notebook());
   align->unset_flags(Gtk::CAN_FOCUS);
   label->unset_flags(Gtk::CAN_FOCUS);
   label->set_use_markup(true);
   frame15->unset_flags(Gtk::CAN_FOCUS);
   frame15->set_shadow_type(Gtk::SHADOW_NONE);
   frame15->set_label_align(0,0);
   frame15->add(*align);
   frame15->set_label_widget(*label);
   nblabel->unset_flags(Gtk::CAN_FOCUS);
   notebook1->set_flags(Gtk::CAN_FOCUS);
   notebook1->append_page(*frame15, *nblabel);
   window3->unset_flags(Gtk::CAN_FOCUS);
   window3->set_title("Nodes");
   window3->add(*notebook1);
   align->show();
   label->show();
   frame15->show();
   nblabel->show();
   notebook1->show();
   window3->show();
}

window3_glade::~window3_glade()
{  delete gmm_data;
}
