// generated 2012/12/15 17:58:03 CET by danilo@dm1.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- wmpSniffer-new.glade
// for gtk 2.24.10 and gtkmm 2.24.2
//
// Please modify the corresponding derived classes in ./src/window1.hh and./src/window1.cc

#ifndef _WINDOW1_GLADE_HH
#  define _WINDOW1_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/treeview.h>
#include <gtkmm/scrolledwindow.h>
#include <gtkmm/radiobutton.h>
#include <gtkmm/box.h>
#include <gtkmm/alignment.h>
#include <gtkmm/entry.h>
#include <gtkmm/button.h>

class window1_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Window * window1;
        class Gtk::TreeView * treeview1;
        class Gtk::ScrolledWindow * scrolledwindow4;
        class Gtk::RadioButton * token_rb;
        class Gtk::RadioButton * aut_rb;
        class Gtk::RadioButton * message_rb;
        class Gtk::RadioButton * drop_rb;
        class Gtk::RadioButton * all_rb;
        class Gtk::HBox * hbox10;
        class Gtk::Alignment * alignment5;
        class Gtk::Entry * entry1;
        class Gtk::Button * button10;
        class Gtk::Button * button11;
        class Gtk::Button * button12;
        class Gtk::HBox * hbox11;
        class Gtk::VBox * vbox7;
protected:
        
        window1_glade();
        
        ~window1_glade();
private:
        virtual void on_button10_clicked() = 0;
        virtual void on_button11_clicked() = 0;
        virtual void on_button12_clicked() = 0;
};
#endif
